### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by gabrielnic** [dfinity/vscode-motoko#11]
It would be great if the code formatter work. 
I'm talking about the integrated one that works with this shortcuts.

On Windows Shift + Alt + F
On Mac Shift + Option + F
On Linux Ctrl + Shift + I

**Comment by kritzcreek** [comment]
> It would be great if the code formatter work.

Agreed!

> I'm talking about the integrated one that works with this shortcuts.

Well those shortcuts just trigger some external formatting tool, so really the only thing that's "integrated" is the shortcuts.

I'm working on the tooling and infrastructure to make writing a nice formatter possible, so it is on my radar, but it's still a while until we'll have that. I'll close this issue because it's not really something that happens in the VSCode plugin, but I'll ping you in here once we've actually got the functionality.
