### ISSUE TITLE
vessel.dhall in parent directory

### ISSUE THREAD

**Issue by borovan** [dfinity/vscode-motoko#66]
test/vessel.dhall :

```
let mainVessel = ../vessel.dhall

in mainVessel
  with dependencies = mainVessel.dependencies # [ "matchers" ]

```

![image](https://user-images.githubusercontent.com/84897664/194846040-e359ab9e-2669-4c6d-a99d-332005b7cb79.png)

This is after the installation of 

https://github.com/kritzcreek/motoko-matchers/tree/master/src

I followed CanDB's way of installing this, and I haven't done this ever before!

**Comment by rvanasa** [comment]
As quick fix, I would recommend adding `matchers` to the main dependency list and removing the Vessel config from the test directory. I'll back you up in calling this a "best practice" compared to having multiple `vessel.dhall` files throughout the project. 

In the future, Vessel will likely have an equivalent to npm's "devDependencies" for these sorts of situations.

**Comment by borovan** [comment]
yup, that works, thanks!  No errors now (other than my own)

**Comment by rvanasa** [comment]
Reopening as a follow-up from #90.

**Comment by ByronBecker** [comment]
> I'll back you up in calling this a "best practice" compared to having multiple `vessel.dhall` files throughout the project.

If we're moving in the direction of extending vessel to allow for a test/dev-depencies in the vessel.dhall this makes sense. If the recommendation though is a single parent file (no nesting), then imo vessel could enforce this and throw an error (i.e. I can't reference another vessel file)

What about a collections type of repository with multiple imports, where import might have its own dependencies?

I'd love to see the an opinionated and in sync position between vessel and the vs-code extension with respect to laying out my dependencies. A vision for where you see vessel going in the future (or if you guys are building a brand new, different package manager) will help a lot as well. Then I can update my templates, examples, and existing projects accordingly.

**Comment by rvanasa** [comment]
The main holdup with Vessel is that almost any meaningful change would break backwards compatibility. I am hoping to add `devDependencies` as soon as possible (https://github.com/dfinity/vessel/pull/61), but we might need to release this as part of a breaking 1.x version of Vessel. 

My vision for VS  Code + Vessel is that you could manage dependencies directly within the IDE (which has the simplest UX when everything is defined in the root directory). However, especially since we are running into blockers for this, I will also try to support the nested package-set design pattern (which is also currently used in the Motoko base library). This is a very nuanced technical challenge, so I will try to include a partial solution in the meantime to unblock the most common use cases. 

It's also worth noting that we might be eventually start shipping Vessel directly within dfx and/or the VS Code extension, which would reduce the importance of full backwards compatibility.
