### ISSUE TITLE
Clicking on errors in console should jump to correct column, not just line

### ISSUE THREAD

**Issue by mymikemiller** [dfinity/vscode-motoko#89]
When an error is printed to the console. it includes both the line and column number. Clicking on the error jumps the cursor to the correct line, but puts it at the beginning of the line, column 0. I often have to count characters to see in more detail where the error occurred. Ideally I wouldn't have to do this manual step, and the cursor would jump to the correct column as printed, not just the line.

**Comment by rvanasa** [comment]
Good point! I'll look into this. What version of `dfx` are you using?

**Comment by mymikemiller** [comment]
The latest, 0.11.2. And the latest version of all the packages, 0.14.0.
It’s been this way since I started using the extension when it first came
out. Minor complaint, but it would certainly save me some time when
addressing errors.

**Comment by rvanasa** [comment]
Closing because this is hopefully no longer needed given recent improvements to the extension. If you still think that this would save you time on the latest version (0.7.2), feel free to ping this issue and I'll re-open in [dfinity/motoko](https://github.com/dfinity/motoko) (which is where we could change the error message format).
